version: '3.8'

services:
  wdio:
    build: .
    container_name: wdio-tests
    shm_size: '2gb'
    environment:
      - BASE_URL=https://demoqa.com
    ports:
      - '5050:5050'
    volumes:
      - ./allure-report:/allure-report
